Vectrix Engine: Vectrix::Json Class Reference
Vectrix::Json Class Reference
Provides static methods for parsing JSON from strings or files.
#include <Json.h>
Public Static Functions
static JsonValue parse (const std::string &fileData)
Parses a JSON string and returns the root JsonValue.
static JsonValue load (const std::string &filePath)
Loads a JSON file from disk and parses its contents.
Detailed Description
Provides static methods for parsing JSON from strings or files.
Note
All methods are static; no instance of JSON is needed.
Definition at line 177 of file Json.h.
Functions
load()
JsonValue Vectrix::Json::load (const std::string & filePath) static
Loads a JSON file from disk and parses its contents.
Parameters
filePath Path to the JSON file.
Returns
The root JsonValue representing the parsed JSON.
Note
If the file cannot be opened or parsed, an error is logged.
Definition at line 9 of file Json.cpp.
References parse().
Referenced by Vectrix::Profiler::isCompatible().
parse()
JsonValue Vectrix::Json::parse (const std::string & fileData) static
Parses a JSON string and returns the root JsonValue.
Parameters
fileData The JSON string to parse.
Returns
The root JsonValue representing the parsed JSON.
Note
On parsing error, the behavior is undefined (likely an assertion or error log).
Definition at line 13 of file Json.cpp.
Referenced by load().
The documentation for this class was generated from the following files:
Vectrix/src/Vectrix/Utils/Json.h
Vectrix/src/Vectrix/Utils/Json.cpp