Vectrix Engine: Vectrix::TextureManager Class Reference
Vectrix::TextureManager Class Reference
Manages textures.
#include <TextureManager.h>
Public Member Functions
std::shared_ptr< Texture > get (const std::string &name)
This function is used to get a texture previously created.
std::vector< std::shared_ptr< Texture > > getAll ()
This function is used to get all the texture previously created.
std::vector< std::pair< std::string, std::shared_ptr< Texture > > > getAllWithName ()
This function is used to get all the texture previously created with their names.
Public Static Functions
static std::shared_ptr< Texture > getNotFoundTexture ()
Use when a texture can't be found or is not compatible This function return a Ref to a texture that is used by the engine when it cannot found a texture.
static TextureManager & instance ()
Return a reference to the instance of this class.
static std::shared_ptr< Texture > createTexture (const std::string &name, const std::string &path)
Function to create a new texture.
Detailed Description
Manages textures.
Definition at line 18 of file TextureManager.h.
Constructors
~TextureManager()
Vectrix::TextureManager::~TextureManager ()
Definition at line 24 of file TextureManager.cpp.
Functions
createTexture()
std::shared_ptr< Texture > Vectrix::TextureManager::createTexture (const std::string & name, const std::string & path) static
Function to create a new texture.
Parameters
name Name given to the texture
path Path of the texture file
Definition at line 18 of file TextureManager.cpp.
References instance().
get()
std::shared_ptr< Texture > Vectrix::TextureManager::get (const std::string & name)
This function is used to get a texture previously created.
Precondition
A texture with this name must exist
Parameters
name Name of the texture you wanna get
Returns
The texture program with the name you entered
Definition at line 35 of file TextureManager.cpp.
getAll()
std::vector< std::shared_ptr< Texture > > Vectrix::TextureManager::getAll () inline
This function is used to get all the texture previously created.
Returns
The texture programs created
Definition at line 41 of file TextureManager.h.
getAllWithName()
std::vector< std::pair< std::string, std::shared_ptr< Texture > > > Vectrix::TextureManager::getAllWithName () inline
This function is used to get all the texture previously created with their names.
Returns
The texture programs created
Definition at line 49 of file TextureManager.h.
getNotFoundTexture()
std::shared_ptr< Texture > Vectrix::TextureManager::getNotFoundTexture () static
Use when a texture can't be found or is not compatible This function return a Ref to a texture that is used by the engine when it cannot found a texture.
Returns
The default texture
Definition at line 43 of file TextureManager.cpp.
References instance().
instance()
TextureManager & Vectrix::TextureManager::instance () inline static
Return a reference to the instance of this class.
Returns
The instance of the class TextureManager
Definition at line 57 of file TextureManager.h.
Referenced by createTexture(), and getNotFoundTexture().
The documentation for this class was generated from the following files:
Vectrix/src/Vectrix/Rendering/Textures/TextureManager.h
Vectrix/src/Vectrix/Rendering/Textures/TextureManager.cpp