Vectrix Engine: Vectrix::MeshManager Class Reference
Vectrix::MeshManager Class Reference
Manages Mesh.
#include <MeshManager.h>
Public Member Functions
std::shared_ptr< Model > get (const std::string &name)
This function is used to get a mesh previously created.
std::vector< std::shared_ptr< Model > > getAll ()
This function is used to get all the mesh previously created.
std::vector< std::pair< std::string, std::shared_ptr< Model > > > getAllWithName ()
This function is used to get all the mesh previously created with their names.
Public Static Functions
static MeshManager & instance ()
Return a reference to the instance of this class.
static std::shared_ptr< Model > loadModel (const std::string &name, const std::string &path)
Function to load a new mesh.
static std::shared_ptr< Model > createModel (const std::string &name, const std::vector< Vertex > &vertices, const std::vector< uint32_t > &indices)
Function to create a new mesh.
static std::shared_ptr< Model > createModel (const std::string &name, const std::vector< Vertex > &vertices)
Function to create a new mesh.
Detailed Description
Manages Mesh.
Definition at line 20 of file MeshManager.h.
Constructors
~MeshManager()
Vectrix::MeshManager::~MeshManager ()
Definition at line 20 of file MeshManager.cpp.
Functions
createModel() [1/2]
std::shared_ptr< Model > Vectrix::MeshManager::createModel (const std::string & name, const std::vector< Vertex > & vertices) static
Function to create a new mesh.
Parameters
name Name given to the mesh
vertices The vertices of the mesh
Returns
A reference to the model that was created
Definition at line 42 of file MeshManager.cpp.
References Vectrix::Application::instance(), instance(), VC_PROFILER_FUNCTION, and Vectrix::Application::window().
createModel() [2/2]
std::shared_ptr< Model > Vectrix::MeshManager::createModel (const std::string & name, const std::vector< Vertex > & vertices, const std::vector< uint32_t > & indices) static
Function to create a new mesh.
Parameters
name Name given to the mesh
vertices The vertices of the model
indices The indices of the model
Returns
A reference to the model that was created
Definition at line 35 of file MeshManager.cpp.
References Vectrix::Application::instance(), instance(), VC_PROFILER_FUNCTION, and Vectrix::Application::window().
get()
std::shared_ptr< Model > Vectrix::MeshManager::get (const std::string & name)
This function is used to get a mesh previously created.
Precondition
A mesh with this name must exist
Parameters
name Name of the mesh you wanna get
Returns
The mesh program with the name you entered
Definition at line 55 of file MeshManager.cpp.
getAll()
std::vector< std::shared_ptr< Model > > Vectrix::MeshManager::getAll () inline
This function is used to get all the mesh previously created.
Returns
The mesh programs created
Definition at line 36 of file MeshManager.h.
getAllWithName()
std::vector< std::pair< std::string, std::shared_ptr< Model > > > Vectrix::MeshManager::getAllWithName () inline
This function is used to get all the mesh previously created with their names.
Returns
The mesh programs created
Definition at line 44 of file MeshManager.h.
instance()
MeshManager & Vectrix::MeshManager::instance () inline static
Return a reference to the instance of this class.
Returns
The instance of the class MeshManager
Definition at line 52 of file MeshManager.h.
Referenced by createModel(), createModel(), and loadModel().
loadModel()
std::shared_ptr< Model > Vectrix::MeshManager::loadModel (const std::string & name, const std::string & path) static
Function to load a new mesh.
Parameters
name Name given to the mesh
path Path of the mesh file (OBJ file)
Returns
A reference to the model that was loaded
Definition at line 27 of file MeshManager.cpp.
References Vectrix::Application::instance(), instance(), VC_PROFILER_FUNCTION, and Vectrix::Application::window().
The documentation for this class was generated from the following files:
Vectrix/src/Vectrix/Rendering/Mesh/MeshManager.h
Vectrix/src/Vectrix/Rendering/Mesh/MeshManager.cpp