Vectrix Engine: Vectrix::Renderer Class Reference
Vectrix::Renderer Class Reference
Central rendering manager for 3D scenes.
#include <Renderer.h>
Public Static Functions
static void beginScene (PerspectiveCamera &camera)
Start rendering a scene with the given camera.
static void endScene ()
End the current rendering scene.
static void submit (Shader &shader, const std::shared_ptr< VertexArray > &vertexArray, const Transform &transform=Transform{ glm::vec3(0.0f), glm::vec3(1.0f), glm::vec3(0.0f) })
Submit geometry with transform.
static void submit (Shader &shader, const Model &model)
Submit a complete model.
static RendererAPI::API getAPI ()
Get current graphics API.
static SceneData & getSceneData ()
Get current scene data.
Detailed Description
Central rendering manager for 3D scenes.
Provides static methods for scene-based rendering. All rendering must occur between BeginScene() and EndScene() calls.
Definition at line 24 of file Renderer.h.
Functions
beginScene()
void Vectrix::Renderer::beginScene (PerspectiveCamera & camera) static
Start rendering a scene with the given camera.
Parameters
camera Camera to use for view/projection matrices
Definition at line 9 of file Renderer.cpp.
References Vectrix::RendererAPI::getAPI(), and VC_PROFILER_FUNCTION.
endScene()
void Vectrix::Renderer::endScene () static
End the current rendering scene.
Definition at line 19 of file Renderer.cpp.
References Vectrix::RendererAPI::getAPI(), and VC_PROFILER_FUNCTION.
getAPI()
RendererAPI::API Vectrix::Renderer::getAPI () inline static
Get current graphics API.
Returns
The active rendering API
Definition at line 69 of file Renderer.h.
References Vectrix::RendererAPI::getAPI().
Referenced by Vectrix::IndexBuffer::create(), Vectrix::VertexArray::create(), and Vectrix::VertexBuffer::create().
getSceneData()
SceneData & Vectrix::Renderer::getSceneData () inline static
Get current scene data.
Returns
Reference to active scene data
Definition at line 74 of file Renderer.h.
submit() [1/2]
void Vectrix::Renderer::submit (Shader & shader, const Model & model) static
Submit a complete model.
Parameters
shader Shader to use
model Model to render
Definition at line 37 of file Renderer.cpp.
References Vectrix::Model::getTransform(), Vectrix::Model::getVertexArray(), submit(), and VC_PROFILER_FUNCTION.
submit() [2/2]
void Vectrix::Renderer::submit (Shader & shader, const std::shared_ptr< VertexArray > & vertexArray, const Transform & transform = Transform{ glm::vec3(0.0f), glm::vec3(1.0f), glm::vec3(0.0f) }) static
Submit geometry with transform.
Parameters
shader Shader to use
vertexArray Geometry to render
transform Transform to apply (position, scale, rotation)
Deprecated
Will be removed when the material system will be created
Definition at line 28 of file Renderer.cpp.
References Vectrix::RendererAPI::getAPI(), and VC_PROFILER_FUNCTION.
Referenced by submit().
The documentation for this class was generated from the following files:
Vectrix/src/Vectrix/Rendering/Renderer.h
Vectrix/src/Vectrix/Rendering/Renderer.cpp