Vectrix Engine: Vectrix::JsonValue Class Reference
Vectrix::JsonValue Class Reference
Represents any JSON value (null, boolean, number, string, array, object).
#include <Json.h>
Public Member Functions
JsonValue ()
Constructs a null JSON value (default).
JsonValue (const std::string &value)
Constructs a JSON string value.
JsonValue (double value)
Constructs a JSON number value.
JsonValue (bool value)
Constructs a JSON boolean value.
JsonValue (const JsonArray &value)
Constructs a JSON array value.
JsonValue (const JsonObject &value)
Constructs a JSON object value.
std::string getString () const
Retrieves the value as a string.
template<typename T>
bool isType () const
Checks if the stored value is of a specific type.
double getDouble () const
Retrieves the value as a double.
bool getBool () const
Retrieves the value as a boolean.
bool isNull () const
Checks if the value is null.
JsonValue operator[] (const std::string &key)
Accesses a member of a JSON object by key.
JsonValue operator[] (size_t index)
Accesses an element of a JSON array by index.
bool contains (const std::string &name) const
Checks if a JSON object contains a specific key.
Detailed Description
Represents any JSON value (null, boolean, number, string, array, object).
Definition at line 40 of file Json.h.
Constructors
JsonValue() [1/6]
Vectrix::JsonValue::JsonValue () inline
Constructs a null JSON value (default).
Definition at line 45 of file Json.h.
Referenced by operator[](), and operator[]().
JsonValue() [2/6]
Vectrix::JsonValue::JsonValue (const std::string & value) inline
Constructs a JSON string value.
Parameters
value The string value
Definition at line 51 of file Json.h.
JsonValue() [3/6]
Vectrix::JsonValue::JsonValue (double value) inline
Constructs a JSON number value.
Parameters
value The double value
Definition at line 57 of file Json.h.
JsonValue() [4/6]
Vectrix::JsonValue::JsonValue (bool value) inline explicit
Constructs a JSON boolean value.
Parameters
value The boolean value
Note
This constructor is explicit to avoid unintended conversions.
Definition at line 64 of file Json.h.
JsonValue() [5/6]
Vectrix::JsonValue::JsonValue (const JsonArray & value) inline
Constructs a JSON array value.
Parameters
value The array of JsonValue elements
Definition at line 70 of file Json.h.
JsonValue() [6/6]
Vectrix::JsonValue::JsonValue (const JsonObject & value) inline
Constructs a JSON object value.
Parameters
value The object (map of string to JsonValue)
Definition at line 76 of file Json.h.
Functions
contains()
bool Vectrix::JsonValue::contains (const std::string & name) const inline nodiscard
Checks if a JSON object contains a specific key.
Parameters
name The key to look for.
Returns
true if the object contains the key, false otherwise.
Note
If the value is not an object, an error is logged and the return value is undefined.
Definition at line 160 of file Json.h.
getBool()
bool Vectrix::JsonValue::getBool () const inline nodiscard
Retrieves the value as a boolean.
Returns
The boolean value if the stored type is bool.
Note
If the value is not a boolean, an error is logged and the return value is undefined.
Definition at line 115 of file Json.h.
getDouble()
double Vectrix::JsonValue::getDouble () const inline nodiscard
Retrieves the value as a double.
Returns
The double value if the stored type is double.
Note
If the value is not a number, an error is logged and the return value is undefined.
Definition at line 104 of file Json.h.
getString()
std::string Vectrix::JsonValue::getString () const inline nodiscard
Retrieves the value as a string.
Returns
The string value if the stored type is string.
Note
If the value is not a string, an error is logged and the return value is undefined.
Definition at line 83 of file Json.h.
Referenced by Vectrix::Profiler::isCompatible().
isNull()
bool Vectrix::JsonValue::isNull () const inline nodiscard
Checks if the value is null.
Returns
true if the value is null, false otherwise.
Definition at line 125 of file Json.h.
isType()
template<typename T> bool Vectrix::JsonValue::isType () const inline nodiscard
Checks if the stored value is of a specific type.
Template Parameters
T The type to check (e.g., std::string, double, bool, nullptr_t, JsonArray, JsonObject).
Returns
true if the value holds type T, false otherwise.
Definition at line 95 of file Json.h.
operator[]() [1/2]
JsonValue Vectrix::JsonValue::operator[] (const std::string & key) inline
Accesses a member of a JSON object by key.
Parameters
key The object key.
Returns
The JsonValue associated with the key.
Note
If the value is not an object, an error is logged and the returned value is undefined.
Definition at line 135 of file Json.h.
References JsonValue().
operator[]() [2/2]
JsonValue Vectrix::JsonValue::operator[] (size_t index) inline
Accesses an element of a JSON array by index.
Parameters
index The zero-based index.
Returns
The JsonValue at the specified index.
Note
If the value is not an array, an error is logged and the returned value is undefined. If the index is out of bounds, std::vector::operator[] behavior is undefined.
Definition at line 148 of file Json.h.
References JsonValue().
The documentation for this class was generated from the following file:
Vectrix/src/Vectrix/Utils/Json.h